### ISSUE TITLE
Merge with bannertime?

### ISSUE THREAD

**Issue by pyramidium** [gbaciulis/generator-bannerlab#1]
Hi there, noticed that you cloned bannertime and implemented some cool features. Would you be up for being a bannertime collaborator and merging these repos?

**Comment by jasonbaciulis** [comment]
Hi, I would prefer to keep it to have more control and play around. If that's ok with you. Or if there is a way to keep bannerlab I could merge.

**Comment by pyramidium** [comment]
Ok fair enough, you could always fork bannertime and then it would be easier to update your fork with any bannertime updates and fixes. You'd still be able to push your own fork to npm as `generator-bannerlab` for personal use.

**Comment by jasonbaciulis** [comment]
Ok, in that case I can merge. But I am fairly new with Git so could you give a little guidance on my next steps?

**Comment by pyramidium** [comment]
Ok so the best thing to do would be to go to https://github.com/pyramidium/generator-bannertime and click on the fork button at the top right of the page. You can push changes you make to your forked repository which should be `https://github.com/`**gbaciulis**`/generator-bannertime`.

You can then request those changes to be merged into generator-bannertime by creating a pull request on the https://github.com/pyramidium/generator-bannertime page. Some more information about pull requests here: https://help.github.com/articles/about-pull-requests/

Feel free to message me if you have any questions 👍

**Comment by jasonbaciulis** [comment]
Thanks for the help. Your contributing docs were actually crystal clear. I made my first pull request.
